#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=250G
#SBATCH --time=24:00:00
#SBATCH --partition=aa100
#SBATCH --gres=gpu:1
#SBATCH --output=log/%j.log
#SBATCH --account=ucb-general
#SBATCH --job-name=scalo_PN
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rey.koki@colorado.edu"

module purge 
module load cuda/11.2 
module load cudnn/8.1

ulimit -s unlimited

source /curc/sw/anaconda3/latest
conda activate alpine 

python train.py 
exit 0
